@baseURL = http://localhost:3000

### Rota pública HOME (acesso livre)
GET {{baseURL}}/
Content-Type: application/json

### Rota pública EVENTOS (acesso livre)
GET {{baseURL}}/events
Content-Type: application/json

### Cadastro de novo usuário
POST {{baseURL}}/auth/register
Content-Type: application/json

{
 "email": "novo@ifrs.edu.br",
  "password": "senha123",
 "role": "user"
}

### Login do novo usuário (pegar o token gerado abaixo)
POST {{baseURL}}/auth/login
Content-Type: application/json

{
 "email": "novo@ifrs.edu.br",
 "password": "senha123"
}

### Login do usuário comum (usuário já existente no banco)
POST {{baseURL}}/auth/login
Content-Type: application/json

{
 "email": "usuario@ifrs.edu.br",
 "password": "123456"
}

### Login do administrador (usuário já existente no banco)
POST {{baseURL}}/auth/login
Content-Type: application/json

{
 "email": "admin@ifrs.edu.br",
 "password": "admin123"
}

### Acesso ao painel (rota protegida, requer token de qualquer usuário
autenticado)
GET {{baseURL}}/protected/dashboard
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGlmcnMuZWR1LmJyIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzU2MzMzMjU3LCJleHAiOjE3NTYzMzY4NTd9.qBvkYosO3o0CXpG6L_LhblWHaBa5e-OsznChx4IIods

### Acesso à área admin (rota protegida, requer token de usuário com role "admin")
GET {{baseURL}}/protected/admin
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGlmcnMuZWR1LmJyIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzU2MzMzMjU3LCJleHAiOjE3NTYzMzY4NTd9.qBvkYosO3o0CXpG6L_LhblWHaBa5e-OsznChx4IIods

### Criar evento (somente admin)
POST {{baseURL}}/protected/events
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGlmcnMuZWR1LmJyIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzU5MzQ3MTMzLCJleHAiOjE3NTkzNTA3MzN9.GGdOpVHz_v3PGoR952J0O8O5N_v_GKGf7sMRy7WJ1xs

{
  "title": "Evento Teste",
  "description": "Descrição do evento teste",
  "start_date": "2025-10-15 09:00:00",
  "end_date": "2025-10-15 17:00:00",
  "location": "Local do evento"
}