@baseURL = http://localhost:3000

### Rota pública HOME (acesso livre)
GET {{baseURL}}/
Content-Type: application/json

### Rota pública EVENTOS (acesso livre)
GET {{baseURL}}/events
Content-Type: application/json

### Cadastro de novo usuário
POST {{baseURL}}/auth/register
Content-Type: application/json

{
 "email": "novo@ifrs.edu.br",
  "password": "senha123",
 "role": "user"
}

### Login do novo usuário (pegar o token gerado abaixo)
POST {{baseURL}}/auth/login
Content-Type: application/json

{
 "email": "novo@ifrs.edu.br",
 "password": "senha123"
}

### Login do usuário comum (usuário já existente no banco)
POST {{baseURL}}/auth/login
Content-Type: application/json

{
 "email": "usuario@ifrs.edu.br",
 "password": "123456"
}

### Login do administrador (usuário já existente no banco)
POST {{baseURL}}/auth/login
Content-Type: application/json

{
 "email": "admin@ifrs.edu.br",
 "password": "admin123"
}

### Acesso ao painel (rota protegida, requer token de qualquer usuário
autenticado)
GET {{baseURL}}/protected/dashboard
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGlmcnMuZWR1LmJyIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzU2MzMzMjU3LCJleHAiOjE3NTYzMzY4NTd9.qBvkYosO3o0CXpG6L_LhblWHaBa5e-OsznChx4IIods

### Acesso à área admin (rota protegida, requer token de usuário com role "admin")
GET {{baseURL}}/protected/admin
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGlmcnMuZWR1LmJyIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzU5ODkzMDIwLCJleHAiOjE3NTk4OTY2MjB9.K_sau3eknAh6rAQizRXQo4qVsG89lZHtWad3vrxKoAI

### Criar evento (somente admin)
POST {{baseURL}}/protected/events
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGlmcnMuZWR1LmJyIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzU5ODkzMDIwLCJleHAiOjE3NTk4OTY2MjB9.K_sau3eknAh6rAQizRXQo4qVsG89lZHtWad3vrxKoAI

{
  "title": "Evento Teste",
  "description": "Descrição do evento teste",
  "start_date": "2025-10-15 09:00:00",
  "end_date": "2025-10-15 17:00:00",
  "location": "Local do evento"
}

### Listar todos os voluntários
GET {{baseURL}}/protected/volunteers
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGlmcnMuZWR1LmJyIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzU5ODkzMDIwLCJleHAiOjE3NTk4OTY2MjB9.K_sau3eknAh6rAQizRXQo4qVsG89lZHtWad3vrxKoAI

### Buscar voluntário por ID
GET {{baseURL}}/protected/volunteers/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGlmcnMuZWR1LmJyIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzU5ODkzMDIwLCJleHAiOjE3NTk4OTY2MjB9.K_sau3eknAh6rAQizRXQo4qVsG89lZHtWad3vrxKoAI

### Criar novo voluntário (admin)
POST {{baseURL}}/protected/volunteers
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGlmcnMuZWR1LmJyIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzU5ODkzMDIwLCJleHAiOjE3NTk4OTY2MjB9.K_sau3eknAh6rAQizRXQo4qVsG89lZHtWad3vrxKoAI

{
  "name": "Voluntario teste",
  "phone": "(54) 99999-9999",
  "email": "voluntario@teste.com"
}

### Atualizar voluntário (admin)
PUT {{baseURL}}/protected/volunteers/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGlmcnMuZWR1LmJyIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzU5ODkzMDIwLCJleHAiOjE3NTk4OTY2MjB9.K_sau3eknAh6rAQizRXQo4qVsG89lZHtWad3vrxKoAI

{
  "name": "VOLUNTARIO TESTE",
  "phone": "(54) 99999-8888",
  "email": "VOLUNTARIO@teste.com"
}

### Excluir voluntário por ID (admin)
DELETE {{baseURL}}/protected/volunteers/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGlmcnMuZWR1LmJyIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzU5ODkzMDIwLCJleHAiOjE3NTk4OTY2MjB9.K_sau3eknAh6rAQizRXQo4qVsG89lZHtWad3vrxKoAI